import { Card, CardBody, CardHeader, Flex, Grid, GridItem, Heading, Text } from '@chakra-ui/react'
import { Inter } from '@next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Yarin App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex alignItems="ceneter" justifyContent="center" height="100%" p={5}>
        <Grid gridGap={5} width="100%" templateAreas={`"header project-a project-b"
                            "project-c project-d project-e"`}>
          <GridItem area="header">
            <Card>
              <CardHeader>
                <Heading size="md" >Yarin Sasson</Heading>
              </CardHeader>
            </Card>
          </GridItem>
          <GridItem area="project-a">
            <Card>
              <CardBody><Text>This is gonna be Amazing</Text></CardBody>
            </Card>
          </GridItem>
          <GridItem area="project-b">
            <Card>
              <CardBody><Text>This is gonna be Amazing</Text></CardBody>
            </Card>
          </GridItem>
          <GridItem area="project-c">
            <Card>
              <CardBody><Text>This is gonna be Amazing</Text></CardBody>
            </Card>
          </GridItem>
          <GridItem area="project-d">
            <Card>
              <CardBody><Text>This is gonna be Amazing</Text></CardBody>
            </Card>
          </GridItem>
          <GridItem area="project-e">
            <Card>
              <CardBody><Text>This is gonna be Amazing</Text></CardBody>
            </Card>
          </GridItem>
        </Grid>
      </Flex>
    </>
  )
}
